### ISSUE TITLE
Return the regular expressions

### ISSUE THREAD

**Issue by SCmkQrK1NhwcWoPJF3FImaqHnG2PqPLWBt2GtSU** [schomery/policy-control#11]
Without regular expressions, this addon is worse than uMatrix (https://addons.mozilla.org/firefox/addon/umatrix/) and Policeman (https://addons.mozilla.org/firefox/addon/policeman/).

**Comment by n8v8R** [comment]
I would concur, that RegExp would make sense, e.g. for jquery. As it is right now each CDN source for jquery would have to be whitelisted individually as opposed with RegExp it could be done globally

**Comment by schomery** [comment]
We will have RegEx support as of the next release.

**Comment by n8v8R** [comment]
Thank you! Working like charm
