### ISSUE TITLE
[Bug report] "wss://" rules dropped

### ISSUE THREAD

**Issue by cryptarch** [schomery/policy-control#13]
When I try to whitelist WebSockets that use the Secure WebSocket protocol `wss://` -- such as those used by [Trello](wss://trello.com) -- the new rule is silently dropped by Policy Control upon saving.

The rules are dropped regardless of input method. Entering them by clicking _Add_ in the Log, typing them manually in the Firefox Addon preferences, and by importing rules from external files all lead to dropped `wss://` rules.

WebSocket rules specified as `https://` are preserved.

My settings are Firefox 57.0 on Linux. I have attached my current rule set, including an offending `wss://` rule.

If `wss://` sockets are not permitted by design for some reason, Policy Socket should be more verbose about explaining this fact, instead of just silently dropping the rules for no reason.

[policy-control-settings.txt](https://github.com/schomery/policy-control/files/1493586/policy-control-settings.txt)

**Comment by schomery** [comment]
Thanks for the report. I'll fix this by next release.

**Comment by cryptarch** [comment]
Thank you :)

**Comment by n8v8R** [comment]
Blocking wss seems to suffer the same issue. Albeit being reported as blocked it actually is not being blocked.
![wss](https://user-images.githubusercontent.com/13611490/34299624-4224e924-e724-11e7-81ce-9e2cbd3d3d3e.png)

**Comment by schomery** [comment]
@n8v8R how can I reproduce this? Note that WebExtension add-ons can only block requests from within a page not those from background scripts (e.g.: from another extension)

**Comment by n8v8R** [comment]
Cannot reproduce it at the moment either, that is FF 57.03 x64 on W10 x64 b16299. What I noticed though now is that `wss` does not show as blocked in the PC log albeit `WebSocket` set to block all. Tested right on this page.

**Comment by schomery** [comment]
Does this page have a `wss` request?

**Comment by n8v8R** [comment]
### Request header
```
Host: live.github.com
Sec-WebSocket-Version: 13
Origin: https://github.com
Sec-WebSocket-Protocol: undefined
Sec-WebSocket-Extensions: permessage-deflate
Sec-WebSocket-Key: 9MgqdndoWdMjECyNxAvIFw==
DNT: 1
Connection: keep-alive, Upgrade
Pragma: no-cache
Upgrade: websocket
```

### Response Header
```
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: oDsArdyhDY4K8O83XflbRw8sMiw=
X-GitHub-Request-Id: F8A2:18B8:E414F:158921:5A47A6CF
```

**Comment by n8v8R** [comment]
Just applied the latest update and the `wss `is now blocked.

**Comment by cryptarch** [comment]
Thank you, this seems to be fixed for me now as well :)
