### ISSUE TITLE
CSP block not working?

### ISSUE THREAD

**Issue by n8v8R** [schomery/policy-control#17]
![csp](https://user-images.githubusercontent.com/13611490/33624473-cf9d4de2-d9f4-11e7-80a1-6df9ab1f6a2d.png)

**Comment by schomery** [comment]
This setting is meant to block reports, not the actual CSP. Blocking CSP is not a good idea. The extension just blocks the reports back to the server (for privacy-concerned users).

**Comment by n8v8R** [comment]
I see, thanks for the explanation though as it was not clear to me. Personally I would like such option however, perhaps have to look into `about:config`
