### ISSUE TITLE
WebAssembly

### ISSUE THREAD

**Issue by n8v8R** [schomery/policy-control#18]
Appreciate if `WebAssembly` could be added to the rules, similar to `WebSocket` already in place

**Comment by schomery** [comment]
No such a resource as far as I know; https://developer.chrome.com/extensions/webRequest#type-ResourceType

**Comment by n8v8R** [comment]
Perhaps not through `webRequest API` but rather the `WebExtension API` like this FF WE does

[wasm-detector in GH](https://github.com/mbnuqw/wasm-detector)

**Comment by schomery** [comment]
The extension looks for URLs that end with ".wasm". I don't think this is a reilable method. `WebAssembly` is part of JS blocking if I recall correctly.

**Comment by n8v8R** [comment]
Closed. Since there is apparently no blocking method in place as of now and it might never be, considering that WebAssembly is indeed a booster for JS and thus to be handled as JS.
