### ISSUE TITLE
[question] development still active?

### ISSUE THREAD

**Issue by ghost** [schomery/policy-control#25]
@schomery 

Is this still being developed?

**Comment by schomery** [comment]
unfortunately not.

**Comment by ghost** [comment]
That is rather unfortunate indeed. :cry:  

Would though however not make sense to let (potential) users know about the fact, here and in the plug-in stores?

**Comment by SecureCloud-biz** [comment]
I agree, I just spent almost 2 hrs typing out (2) issues #30 and #31 ... that's messed up... maybe archive the repo or something... or make a few changes :-)
